# /etc/supervisor/conf.d/agendamento.conf

[program:agendamento-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/agendamento/artisan queue:work database --sleep=3 --tries=3 --max-time=3600 --timeout=90
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/agendamento/storage/logs/worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=3600
